### ISSUE TITLE
dectlk driver doesn't seem to accept full range of parameters

### ISSUE THREAD

**Issue by grnowak** [bytefire/speakup#11]
The dectlk driver doesn't seem to accept adjusting the full range of available parameters. The full discussion of this issue is at:

http://linux-speakup.org/pipermail/speakup/2020-April/062220.html

I don't have a dectalk here, so am unable to help Chime further, or to provide a better perspective on this issue. I believe Oakash has a dectalk to work with. It would be great if this issue could be looked at. Passing parameters to synth_direct just means that speakup will reset them, and therefore can't be a long term every day solution to setting parameters beyond the range that speakup supports. Thanks.

**Comment by sthibaul** [comment]
From reading the log, it looks to me like there is rather some misunderstanding in how one is supposed to configure synths. synth_direct is definitely *not* the proper way to do it. Please see my comments on

http://linux-speakup.org/pipermail/speakup/2020-April/062229.html
http://linux-speakup.org/pipermail/speakup/2020-April/062230.html

**Comment by grnowak** [comment]
I think that the recently introduced inflection speakup parameter seems to solve the problem. So, I'm closing this issue. If this still turns out to be a problem, it can be discussed on the speakup list, or I can reopen this issue again.
