### ISSUE TITLE
Separate out speakup ldisc code into its own module

### ISSUE THREAD

**Issue by bytefire** [bytefire/speakup#4]
Currently spk_ttyio.c file contains speakup ldisc code and other other functionality. We should split this file into two: one to contain ldisc specific code and the other to contain rest.

**Comment by bytefire** [comment]
It seems like N_SPEAKUP is quite specific to speakup system so it is unlikely to be used elsewhere. There is also a closer coupling between speakup ldisc and spk_ttyio: check how spk_ttyio.c:ttyio_in() and spk_ttyio.c:spk_ttyio_receive_buf2() coordinate to receive input.

Therefore refactoring speakup ldisc into its own module would increase complexity while at the same time not provide benefits as we don't expect other systems to use N_SPEAKUP. Not fixing this for now, unless there is stronger reason to do so.

**Comment by sthibaul** [comment]
I was indeed quite wondering about any benefits we might have with it :)

**Comment by bytefire** [comment]
Actually this is was suggested by Alan Cox during a review. But our use of ldisc is different/creative :)
