### ISSUE TITLE
speakup outputs alternately to soft and serial synths when both are loaded

### ISSUE THREAD

**Issue by grnowak** [bytefire/speakup#7]
I thought I'd document this issue here. When both speakup_soft and one of the serial synthesizers such as speakup_dummy are loaded, speakup randomly sends output to both synthesizers at the same time. This issue is known to exist in speakup source in 4.17.x and 4.18.x kernels. It may be in earlier trees though as well. Steps to reproduce are given in the first of the below URLs:

http://linux-speakup.org/pipermail/speakup/2018-June/061417.html

http://linux-speakup.org/pipermail/speakup/2018-October/061481.html

http://linux-speakup.org/pipermail/speakup/2018-October/061482.html

**Comment by sthibaul** [comment]
Could somebody who has had the issue try the attached 
[mix.txt](https://github.com/bytefire/speakup/files/2499594/mix.txt) ?

**Comment by grnowak** [comment]
I've only had a chance to use my newly built kernel for a few minutes,
but Samuel's patch does appear to fix the problem. I will do more
testing in the morning, and will close this issue if this problem has
gone away. This is using the patch Samuel posted to the speakup list
against 4.18.x, 4.18.16 in my case.

**Comment by sthibaul** [comment]
This was submitted on https://marc.info/?l=linux-kernel&m=154032393724211&w=2
